### ISSUE TITLE
inactive links

### ISSUE THREAD

**Issue by slushi66** [pblasquez/weathermapper#12]
Hello,

I have a problem with my weathermap. 

He found my librenms's devices but there are not link : 

https://i.imgur.com/kjaJp7L.png

I installed [weathermap](https://docs.librenms.org/Extensions/Weathermap/) and [weathermapper](https://github.com/pblasquez/weathermapper) 
I did device dependencies 
And configured my links (link properties) so why there are inactive links ?

thank you

**Comment by cron410** [comment]
I have the same issue for all groups except for group 3 which is all of my devices.

```
Generating weathermap configuration to /opt/librenms/html/plugins/Weathermap/configs/mdbc-all.conf
No links found for mdbc-sp, please ensure LibreNMS auto-discovery is enabled and working.
Generating weathermap configuration to /opt/librenms/html/plugins/Weathermap/configs/MDBC.conf
No links found for sp, please ensure LibreNMS auto-discovery is enabled and working.
No links found for test, please ensure LibreNMS auto-discovery is enabled and working.
No links found for tm, please ensure LibreNMS auto-discovery is enabled and working.
librenms@librenms:~/html/plugins/Weathermap/weathermapper$ ls
```

**Comment by pblasquez** [comment]
Hello,

Weathermapper depends on auto-discovery information only, not device dependencies.  Specifically, it uses the 'links' table in the database.  If your devices are not all represented by an XDP/ARP relationship in the database, it will not find any links to build.

Please ensure that XDP/ARP discovery is enabled and running, and keep in mind that ARP discovery is a high intensity setting and will consume a lot of resources. 

@cron410 since you are able to build links when using all of your devices, it may just be that the devices in your other groups do not have their XDP/ARP relationships built.  If you only have XDP enabled, it may be that you need to  enable ARP as well for those devices.
